src/runtime/server/api/session.ts

I replaced `import config from '#config'` with the new `import { useRuntimeConfig } from '#nitro'` due to migration to nitropack by Nuxt 3.
During the migration to nitropack in Nuxt 3, the runtime config can be directly imported from virtual `#nitro` not `#config`.
Resolves: #22

fix: replace #config with #nitro

---

docs/content/3.usage/1.composables.md
docs/content/4.advanced.md

- removed an extra `}` in a code snippet
- replaced *composable* by *middleware*

docs: fix typos

---

CHANGELOG.md
docs/content/_theme.yml
package.json
src/module.ts
yarn.lock

Want to get the 2.0 branch updated specifically for compatibility mode. See changes here https://github.com/nuxt-modules/supabase/pull/70

Update v2 branch with main (fix compatibility mode)

---

src/module.ts

Fixes #46 
Using `build.transpile` for `websocket` package makes any app using this module broken on Cloudflare Workers (unpublishable).
Therefore, we just keep the `viteConfig.optimizeDeps` so it correctly works in development, and doing it as well for builds has 0 bundle cost, so this change should be more than ideal to fix the issue !
**Update**: See https://github.com/nuxt-modules/supabase/pull/84#issuecomment-1271374397

fix: remove websocket transpile during build

---

src/runtime/server/services/serverSupabaseClient.ts

When using supabase as first request via SSR, or API call when no user is logged in, no `token` exists. Content can still be accessible when RLS is set to public.

fix: do not apply token if not exists

---

docs/content/3.usage/1.composables/1.use-supabase-auth-client.md
docs/content/3.usage/1.composables/1.use-supabase-client.md
playground/app.vue
playground/pages/index.vue
playground/pages/me.vue
playground/types/database.types.ts
src/runtime/composables/useSupabaseAuthClient.ts
src/runtime/plugins/supabase.client.ts
src/runtime/plugins/supabase.server.ts

⚠️  This PR involves BREAKING CHANGES ⚠️ 
In order to resolve #114, I have made the choice to separate the `useSupabaseClient` in two other composables:
- The `useSupabaseAuthClient` is dedicated to authentification purpose only. It won't be recreate if your token expires, it is used in the client plugin to listen to `onAuthStateChange` events.
- The `useSupabaseClient` is now only useful for data request.
To avoid regression you just need to use the `useSupabaseAuthClient` instead of the `useSupabaseClient` everywhere you use [Supabase auth methods](https://supabase.com/docs/reference/javascript/auth-signup)
[Documentation](https://supabase.nuxtjs.org/usage/composables/use-supabase-auth-client) has been updated.

feat(composables): add useSubabaseAuthClient

---

src/module.ts

This removes extra (even if negligible) overhead when not using the redirect feature, by not registering the global `auth-redirect` route middleware plugin.

chore(module): conditionally add redirect plugin

---

src/runtime/server/services/serverSupabaseServiceRole.ts

Fixes https://github.com/nuxt-modules/supabase/issues/193
Insure that defaults for `auth` are set on the options passed to createClient when using `serverSupabaseServiceRole`.
Tests not added because existing tests cover the same code.

fix(client): fix persist session warning for `serverSupabaseServiceRole`

---

src/runtime/server/api/session.ts

This PR stores provider access/refresh tokens in cookies, to allow server routes to use provider APIs.
When logging in users with external API scopes for a provider (for example, Github), the application will need access to the provider token to access the provider's API. This token is stored in the `session` object, which is only stored in the client (if I'm not mistaken).
When calling an API in my project, only `sb-access-token` and `sb-refresh-token` cookies are sent, which means that if I want to access Github's API from a server route, I won't be able to do so.
As I see it, there are 2 workarounds for this:
1. Store provider's access/refresh tokens in a Supabse table and access that table from server (vanilla, and cumbersome)
2. Store provider's access/refresh tokens in a cookie, so …

feat: save provider access/refresh tokens in cookies

---

src/runtime/plugins/supabase.client.ts

The cookie provider_token was erroneously assigned the value of `session.access_token`. This fixes it

fix(typo): correct provider_token assignment to cookie

---

src/runtime/composables/useSupabaseUser.ts

This adds an explicit typecast to the returned `user` object from `useSupabaseUser`. When built, the annotation is picked up and added to the `.d.ts` file. Since 1.0.0-0 the type was inferred as `any`. 
There are no tests for the `.d.ts` output. Probably this is caused by a bug upstream and needs a test there.

Add explicit user type to work around build issue

---

docs/content/2.get-started.md
src/module.ts

When using `runtimeConfig` environment variables, everything works, but a warning appear.
This PR test key and url after having merged module with `runtimeConfig` to detect if they are provided.

fix: do not warn when using runtimeConfig to set url and key

---

src/runtime/plugins/supabase.client.ts

Don't call `useCookie` in `onAuthStateChange`, as this leads to incorrect behavior and warnings during development.
`useCookie` is called in `onAuthStateChange` which is called outside of the Vue effect scope. This triggers the following warning in dev: `[Vue warn] onScopeDispose() is called when there is no active effect scope to be associated with.`. This warning is muted in prod but the behavior of `useCookie` subtly changes.

fix(client): prevent useCookie usage outside of effect scope

---

docs/content/2.get-started.md
docs/content/3.authentication.md
src/module.ts
src/runtime/plugins/auth-redirect.ts
src/runtime/types/index.d.ts

Added a feature to store the requested route that is outside the scope of the excluded routes. The route is stored in a cookie and disabled by default.
I needed a way to have my application users be able to share a link to a page with users who potentially would not be registered or logged in. This Pull Request adds a cookie that is set when the client tries to hit a route that is not listed in the `redirectOptions.exclude` list, it then sets the cookie equal to the `route.to.fullPath` to include capturing the url parameters.
I couldn't just use the redirectTo when using OAuth because using the `redirect: true` makes the module's middleware leave the route and always report it as `/login`. I needed to capture the route BEFORE the Supabase `auth-redirect.mjs` middleware performed the …

feat(app): added redirect path cookie for use after signin

---

docs/content/2.get-started.md
docs/content/3.authentication.md
docs/content/4.usage/composables/useSupabaseUser.md
playground/nuxt.config.ts
playground/pages/protected.vue
src/runtime/plugins/auth-redirect.ts
src/runtime/types/index.d.ts

Closes #268
Add an `include` option to `RedirectOptions`. If set, only routes matching the supplied regex are considered for redirects.

feat(app): add `include` to `RedirectOptions`

---

playground/pages/user.vue
src/runtime/composables/useSupabaseSession.ts
src/runtime/composables/useSupabaseUser.ts
src/runtime/plugins/supabase.client.ts
src/runtime/plugins/supabase.server.ts

By looking into the code, I realize that composables `useSupabaseUser()` and `useSupabaseSession()` are calling the same Supabase API in order to get almost the same information. 
On both, they call `supabase?.auth.getSession()`. `useSupabaseSession()` get the session like this and `useSupabaseUser()` get the user from the session.
We can improve this by:
- Letting `useSupabaseSession()` fetch the session from Supabase
- Compute the user of `useSupabaseUser()` from `useSupabaseSession()` because session contains the user
We gain an API call and it's a little bit easier to maintain because the value of `useSupabaseUser()` is strongly linked to `useSupabaseSession()` value. Each time the session changes, the user will update automatically.

Only fetch supabase?.auth.getSession() once

---

docs/content/2.get-started.md

This updates the documentation to use the [`nuxi module add` command](https://github.com/nuxt/cli/pull/197) which should simplify docs a bit and also improve user experience as there's no need to add to `nuxt.config` manually.
It's documented [here](https://nuxt.com/docs/api/commands/module#nuxi-module-add).
I may have missed a few spots in the documentation as I'm doing this across the modules ecosystem assisted by the power of regular expressions ✨, so I'd appreciate a review 🙏

docs: use new `nuxi module add` command in installation

---

docs/content/2.get-started.md

Docs change
Supabase CLI changed, it now shows: `Command "typescript" is deprecated, use "gen types --lang=typescript" instead.` when doing `supabase gen types typescript`. This PR changes the docs accordingly.
Docs change so no further actions needed.

[docs] Update 2.get-started.md

---

src/runtime/composables/useSupabaseSession.ts
src/runtime/composables/useSupabaseUser.ts
tsconfig.json

Resolves https://github.com/nuxt-modules/supabase/issues/406, https://github.com/nuxt-modules/supabase/issues/396
Removed `strictNullChecks` from the tsconfig as it may lead to misleading editor type behaviours. Made `useSupabaseSession` and `useSupabaseUser` nullable.

fix(types): nullable composable types

---

src/runtime/plugins/auth-redirect.ts
src/runtime/plugins/supabase.client.ts

Fixes build errors for plugins `src/runtime/plugins/supabase.client.ts` and `src/runtime/plugins/auth-redirect.ts`

fix(types): add explicit type annotations for plugins

---

src/module.ts
src/runtime/server/services/serverSupabaseClient.ts
src/runtime/server/services/serverSupabaseServiceRole.ts

Added explicit type annotations for `serverSupabaseClient` and `serverSupabaseServiceRole` as they lose the `Database` type when building.

fix(types): added explicit types annotations for `serverSupabaseClient` and `serverSupabaseServiceRole`

---

demo/README.md
demo/app.config.ts
demo/components/AppContainer.vue
demo/components/AppHeader.vue
demo/components/LoginCard.vue
demo/nuxt.config.ts
demo/package.json
demo/pages/confirm.vue
demo/pages/index.vue
demo/pages/tasks.vue
demo/pnpm-lock.yaml

The updated Nuxt UI package is not a 100% replacement, but "good" enough - some margins/paddings have been changed, and the dark mode is not inversed on the cards anymore

Replace `@nuxthq/ui` with `@nuxt/ui` in demo project

---

src/runtime/composables/useSupabaseSession.ts
src/runtime/plugins/supabase.server.ts
src/runtime/server/services/serverSupabaseSession.ts

This PR addresses a warning that occurs when calling `supabase.auth.getSession()` on the server:
```
WARN  Using the user object as returned from supabase.auth.getSession() or from some supabase.auth.onAuthStateChange() events could be insecure! This value comes directly from the storage medium (usually cookies on the server) and may not be authentic. Use supabase.auth.getUser() instead, which authenticates the data by contacting the Supabase Auth server.
```
To resolve this, the `user` property is removed from the session object within the server plugin. This prevents the `user` prop from being accessed and stops the warning from being logged.
An alternative approach, without deleting the `user` object, could be:
```ts
useSupabaseSession().value = session
? {
access_token: …
```

fix: ssr getSession warning

---

docs/content/4.usage/services/3.serverSupabaseSession.md

Its not really clear in both the Supabase and these docs that serverSupabaseSession is unsafe for checking if the user is logged in or not. This note might prevent some developers from making this mistake.

Add security advise to serverSupabaseSession

---

package.json
pnpm-lock.yaml
src/runtime/composables/useSupabaseClient.ts
src/runtime/plugins/supabase.client.ts
src/runtime/plugins/supabase.server.ts

1. Updated some dependencies (incl. `@supabase/ssr`)
2. I moved the `provide` for the client in both plugins before the first `await` (instead of returning it at the end). This is because we found some Sentry logs that showed one of our plugins with an `async setup` method not having provided early enough which lead to "Right side of assignment could not be destructured" even though I would have expected that the app only runs once the plugins' `setup` is finished and everything is provided. Since I made the change, the errors have stopped. @larbish is this necessary or how could the provide have gone wrong in an async context?

chore: update dependencies & provide client earlier

---

docs/content/2.get-started.md

I tried adding `/api/scan/*` to my `supabase.redirectOptions.exclude` array in my Nuxt config, but it did not match a server route (`server/api/scan/[id].ts`), whereas `/api/scan/**` seems to work – let me know if this is expected or i'm "holding it wrong". If this is the expected usage, then I've proposed a docs update.
_P.S. Thanks for the module! :3_

docs(redirectOptions): fix exclude wildcard example

---

demo/README.md

http://localhost:3000/auth/callback?error=server_error&error_code=500&error_description=Error+getting+user+profile+from+external+provider otherwise

Update README.md to include email permission requirement

---

src/runtime/server/services/serverSupabaseServiceRole.ts

I'm having issues in production because my environment variables are not actually being respected. No problems locally while developing, but when I look at the values that are being pulled for `serviceKey` and `url` in production, they are not receiving the override that I expect from my environment variables. I believe this is the culprit. 
Per [Nuxt's documentation](https://nuxt.com/docs/guide/going-further/runtime-config#server-routes): 
> Giving the event as argument to useRuntimeConfig is optional, but it is recommended to pass it to get the runtime config overwritten by environment variables at runtime for server routes.
I have tested this using [patch-package](https://www.npmjs.com/package/patch-package#benefits-of-patching-over-forking) and confirmed that doing this fixes the …

Pass H3Event into useRuntimeConfig for serverSupabaseServiceRole

---

docs/content/2.get-started.md
docs/content/3.authentication.md
docs/content/4.usage/composables/useSupabaseCookieRedirect.md
src/module.ts
src/runtime/composables/useSupabaseCookieRedirect.ts
src/runtime/plugins/auth-redirect.ts
src/runtime/plugins/supabase.client.ts
src/runtime/plugins/supabase.server.ts
src/runtime/server/services/serverSupabaseClient.ts
src/types/index.ts

The following issues are all more or less related to the same set of problems. This pull request aims to add options that solve all of these problems, and make the module more flexible and consistent!
Currently, the`createBrowserClient` [overrides multiple client options](https://github.com/supabase/ssr/blob/ef429dfbd1dc9f446bdef009717dfc6d8a2e3c85/src/createBrowserClient.ts#L140), causing multiple issues:
- You can't set `detectSessionInUrl` to false in the client options (this is caused from the override). In my static site, I need to handle the session manually.
- [Issue: Setting persistSession: false still persists auth session](https://github.com/nuxt-modules/supabase/issues/390) (this is caused from the override)
- [Issue: The module doesn't recognize …

 Fix `clientOptions` issues and cookie problems

---

src/runtime/server/services/serverSupabaseClient.ts

Similar to https://github.com/nuxt-modules/supabase/pull/450, I faced issues when deploying this module to a Cloudflare worker. It would not find the supabase runtime config on the server-side.
I tried to reproduce it, and passing the event makes the runtime config work correctly
```ts
return {
a: useRuntimeConfig().public.supabase, // <- missing keys
b: useRuntimeConfig(event).public.supabase, // <- works
};
```

Pass H3Event into useRuntimeConfig for serverSupabaseClient

---

src/module.ts

The generated types file `.nuxt/types/supabase-database.d.ts` contains broken paths examples I tested
|path|nuxt.config.ts|supabase-database.d.ts|
|:--|:--|:--|
|`/app/types/database.types.ts`|`~/types/database.types.ts`|`../..app/types/database.types.ts`
|`/types/database.types.ts`|`~~/types/database.types.ts`|`../..types/database.types.ts`
The problem is the missing `/` before the directory name.
So I instead of using a string replacement, it now uses `unjs/pathe` relative to resolve the path correctly 
Resolves: #515
How can I add tests for this kind of change? I tested these changes manually in my Nuxt 4 Project.
Manual testing:
1. Run `npm run dev:prepare`
2. Take a look at playgrounds `.nuxt/types/supabase-database.d.ts` file. Wrong path is used.
```ts
export * from …
```

fix: use "unjs/pathe" to make the exported type use relative path

---

demo/README.md

This PR updates the README file in the "demo" folder as in #507

docs(demo/readme): clarify demo docs regarding to issue #507

---

src/runtime/plugins/supabase.server.ts
src/runtime/server/services/serverSupabaseClient.ts
src/runtime/utils/cookies.ts

This PR implements a defensive guard for SSR cookie writes.  
Previously, `setAll` unconditionally attempted to call `setCookie` even when the H3/Node response headers had already been sent. This caused runtime errors and unhandledRejection spam during token refresh in dev after idle:
```
ERROR Cannot remove headers after they are sent to the client
at ServerResponse.removeHeader (node:_http_outgoing:848:11)
at setCookie (h3/dist/index.mjs:615:18)
at node_modules/@nuxtjs/supabase/dist/runtime/plugins/supabase.server.js:31:111
at Array.forEach (<anonymous>)
at setAll (.../node_modules/@nuxtjs/supabase/dist/runtime/plugins/supabase.server.js:31:38)
at applyServerStorage (.../@supabase/ssr/dist/module/cookies.js:274:9)
at async Object.callback …
```

fix(#518): guard cookie writes when response headers already sent

---

docs/content/3.services/1.serverSupabaseClient.md

Update data fetching URL
Previous anchor tag was broken (was changed), so I updated it.

Update data fetching URL
