nuxt-modules/supabase

- docs/pages/2.usage.md
Right now when copy pasting the code from here https://github.com/nuxt-community/supabase-module/blob/bf68299c2313eab79f1753b8f498384c1676439c/docs/pages/2.usage.md?plain=1#L30 into a Nuxt project, I see the following warning:
by using the shorthand object syntax `{ provider }` , it effectively is a UserCredentials object
> docs: improve code example

- docs/content/1.index.md
- docs/content/2.get-started.md
- docs/content/3.usage/1.composables.md
- docs/content/3.usage/1.services.md
- src/module.ts
- src/runtime/server/services/index.ts
- src/runtime/server/services/serverSupabaseClient.ts
- src/runtime/server/services/serverSupabaseServiceRole.ts
> feat(server): service role client to bypass RLS

- src/module.ts
Temporary fix to ensure regression won't happen. Closes #54
> fix: transpile `@supabase/` packages

- docs/content/3.usage/2.services.md
> docs: Update 2.services.md

- src/module.ts
In https://github.com/nuxt/framework/pull/7116 we made a breaking change allowing modules to use RC constraints. This PR fixes this.
> fix: update nuxt compatibility

- src/runtime/composables/useSupabaseClient.ts
To be able to pass `Database` typings to the Supabase Client when using this module.
As in their [Release Notes](https://supabase.com/docs/reference/javascript/release-notes#typescript-support).
```ts
import type { Database } from '~/types'
const client = useSupabaseClient<Database>()
```
> feat: typed supabase client

- docs/content/3.usage/1.composables/1.use-supabase-client.md
> Fix spelling mistake

- docs/content/3.usage/2.services/2.server-supabase-user.md
> Simplify and clarify intro explanation

- src/runtime/plugins/auth-redirect.ts
- src/runtime/plugins/supabase.server.ts
- src/runtime/utils/redirect.ts
> fix(redirect): use router instead of navigateTo

- docs/content-v1/3.usage/1.composables/1.use-supabase-client.md
- docs/content/2.get-started.md
- docs/content/3.usage/1.composables/1.use-supabase-auth-client.md
- docs/content/3.usage/1.composables/1.use-supabase-client.md
- docs/content/3.usage/1.composables/2.use-supabase-user.md
- docs/content/3.usage/2.services/1.server-supabase-client.md
- docs/content/3.usage/2.services/2.server-supabase-service-role.md
- docs/content/3.usage/2.services/2.server-supabase-user.md
[DOCS]
- Update Nuxt & Supabase links that are broken
- Fix some typos along the way
> docs: update links and fix typos

- docs/content/2.get-started.md
> chore: fix typos

- docs/content/3.usage/1.composables/1.use-supabase-auth-client.md
> Correct grammar errors

- src/runtime/composables/useSupabaseAuthClient.ts
> perf(useSupabaseAuthClient): avoid declaring unused variables

- docs/content/3.usage/1.composables/1.use-supabase-auth-client.md
This change adds the `setup` attribute to the script tag 😄 and reorders the order of the tags for the sake of consistency.
> add: setup attr to script tag

- package.json
- src/runtime/composables/useSupabaseUser.ts
- src/runtime/plugins/supabase.client.ts
- src/runtime/server/services/serverSupabaseUser.ts
> Release 1.0.1

- docs/app.config.ts
The link to supabase has wrong lablel. This PR fixes it.
> docs: fix Supabase link label

- src/module.ts
> fix priority of supabase options made by defu

- src/runtime/server/services/serverSupabaseClient.ts
Update serverSupabaseClient to use clientOptions from nuxt runtime config.
Allows server to connect to user defined schema other than public by setting clientOptions db schema
Resolves #275
This is my first pull request and I am not sure where the tests are if there are any.
> Use clientOptions fix#275 - Allow connection to user schema other than public

- docs/content/index.yml
- [x ] Bug fix (a non-breaking change which fixes an issue)
I'm just changing the vue js website link because the existing link is redirecting to website which don't exist
It's the correct link for vue js composables
- [x ] My change requires a change to the documentation.
> Fix the vuejs website link

- README.md
When trying to contribute, I noticed that there was `run` missing in `npm run build` command. This fixes the readme.
`npm build` -> `npm run build`
Fixes building command for npm
> Fix typo in #development section

- package.json
- pnpm-lock.yaml
- src/module.ts
I updated Nuxt to 3.14 and supabase-js to the latest version too
> Update Nuxt and `supabase-js`

- package.json
- pnpm-lock.yaml
Update `supabase-js` to 2.47.0 to use accessToken callback for auth in realtime (https://github.com/supabase/supabase-js/pull/1320)
> Update `supabase-js` to (hopefully) fix realtime issue

- src/runtime/plugins/supabase.client.ts
> fix: do not set states on client

- docs/content/1.getting-started/2.authentication.md
> docs: add reset password docs
